//
//  stdlib_operators.swift
//
//  Bridging code for primitive handlers. This file is auto-generated; do not edit directly.
//

import Foundation

func stdlib_loadOperators(into registry: OperatorRegistry) {
    registry.add([.expression, .keyword("&"), .expression], 340, .left)
    registry.add([.expression, .keyword(["*", "×"]), .expression], 1296, .left)
    registry.add([.expression, .keyword(["+", "＋"]), .expression], 1290, .left)
    registry.add([.expression, .keyword(["-", "－", "−", "﹣"]), .expression], 1290, .left)
    registry.add([.expression, .keyword(["/", "÷"]), .expression], 1296, .left)
    registry.add([.expression, .keyword("<"), .expression], 540, .left)
    registry.add([.expression, .keyword(["=", "=="]), .expression], 540, .left)
    registry.add([.expression, .keyword(">"), .expression], 540, .left)
    registry.add([.expression, .keyword("AND"), .expression], 398, .left)
    registry.add([.keyword("NOT"), .expression], 400, .left)
    registry.add([.expression, .keyword("OR"), .expression], 396, .left)
    registry.add([.expression, .keyword("XOR"), .expression], 394, .left)
    registry.add([.expression, .keyword(["^", "to_the_power_of"]), .expression], 1300, .right)
    registry.add([.expressionLabeled("element_type"), .keyword("after"), .expressionLabeled("expression")], 1126, .right)
    registry.add([.keyword(["any", "some"]), .expression], 1130, .left)
    registry.add([.expression, .keyword("as"), .expression], 350, .left)
    registry.add([.expression, .keyword(["at", "index"]), .expression], 1110, .left)
    registry.add([.expressionLabeled("element_type"), .keyword("before"), .expressionLabeled("expression")], 1126, .right)
    registry.add([.keyword("beginning")], 1106, .left)
    registry.add([.expression, .keyword("begins_with"), .expression], 542, .left)
    registry.add([.expression, .keyword("contains"), .expression], 542, .left)
    registry.add([.expression, .keyword("div"), .expression], 1296, .left)
    registry.add([.keyword("end")], 1106, .left)
    registry.add([.expression, .keyword("ends_with"), .expression], 542, .left)
    registry.add([.keyword(["every", "all"]), .expression], 1130, .left)
    registry.add([.keyword("first"), .expression], 1130, .left)
    registry.add([.expression, .keyword("from"), .expression], 1110, .left)
    registry.add([.expression, .keyword("id"), .expression], 1110, .left)
    registry.add([.keyword("if"), .expressionLabeled("test"), .keyword("then"), .expressionLabeled("then"), .optional([.keyword("else"),.expressionLabeled("else")])], 101, .left)
    registry.add([.expression, .keyword("is_a"), .expression], 540, .left)
    registry.add([.expression, .keyword("is_after"), .expression], 540, .left)
    registry.add([.expression, .keyword("is_before"), .expression], 540, .left)
    registry.add([.expression, .keyword("is_in"), .expression], 542, .left)
    registry.add([.expression, .keyword(["is_not_after", "is_before_or_same_as"]), .expression], 540, .left)
    registry.add([.expression, .keyword(["is_not_before", "is_same_as_or_after"]), .expression], 540, .left)
    registry.add([.expression, .keyword("is_not_same_as"), .expression], 540, .left)
    registry.add([.expression, .keyword("is_same_as"), .expression], 540, .left)
    registry.add([.keyword("last"), .expression], 1130, .left)
    registry.add([.keyword("middle"), .expression], 1130, .left)
    registry.add([.expression, .keyword("mod"), .expression], 1296, .left)
    registry.add([.expression, .keyword("named"), .expression], 1110, .left)
    registry.add([.keyword(["negative", "-", "－", "−", "﹣"]), .expressionLabeled("right")], 1298, .left, reductionForNegativeOperator)
    registry.add([.expression, .keyword("of"), .expression], 1100, .right)
    registry.add([.keyword(["positive", "+", "＋"]), .expressionLabeled("right")], 1298, .left, reductionForPositiveOperator)
    registry.add([.keyword("repeat"), .expressionLabeled("condition"), .keyword("while"), .expressionLabeled("action")], 101, .left)
    registry.add([.expression, .keyword("returning"), .expression], 300, .left)
    registry.add([.keyword("set"), .expressionLabeled("name"), .keyword("to"), .expressionLabeled("to")], 80, .left)
    registry.add([.keyword("tell"), .expressionLabeled("target"), .keyword("to"), .expressionLabeled("action")], 101, .left)
    registry.add([.expression, .keyword(["thru", "through"]), .expression], 1120, .left)
    registry.add([.keyword("to"), .expressionLabeled("interface"), .keyword("run"), .expressionLabeled("action")], 80, .left)
    registry.add([.keyword("when"), .expressionLabeled("interface"), .keyword("run"), .expressionLabeled("action")], 80, .left)
    registry.add([.keyword("while"), .expressionLabeled("condition"), .keyword("repeat"), .expressionLabeled("action")], 101, .left)
    registry.add([.expression, .keyword(["whose", "where"]), .expression], 1110, .left)
    registry.add([.expression, .keyword(["≠", "<>"]), .expression], 540, .left)
    registry.add([.expression, .keyword(["≤", "<="]), .expression], 540, .left)
    registry.add([.expression, .keyword(["≥", ">="]), .expression], 540, .left)
}
